IBM watson translator integration
lpawelcz/ar-translator pull request #4
Opened 2021-01-06 23:34 UTC by lpawelcz

2021-01-06 23:38 UTC, wojtasiq approved these changes

2021-01-06 23:51 UTC, belikePac requested changes
1) Change class name to TextTranslator instead TextTransl (where 'l' looks like '1')
2) Try upgrading flutter_ibm_watson to 0.0.4 as it's the newest one.

2021-01-07 00:01 UTC, lpawelcz commented on pubspec.yaml
> +  flutter_ibm_watson: ^0.0.1
NOTE: Version change requested by @belikePac

2021-01-07 00:01 UTC, lpawelcz commented on lib/translation/text-transl.dart
> +class TextTransl {
NOTE: Change to `TextTranslator` as @belikePac  suggested

2021-01-07 00:02 UTC, wojtasiq approved these changes

2021-01-07 00:06 UTC, lpawelcz commented on pubspec.yaml
> +  flutter_ibm_watson: ^0.0.1
changed to 0.04v

2021-01-07 00:06 UTC, lpawelcz commented on lib/translation/text-transl.dart
> +class TextTransl {
renamed

2021-01-07 00:08 UTC, lpawelcz commented
Applied changes requested in @belikePac review

2021-01-07 00:22 UTC, belikePac approved these changes
Very good work!

2021-01-07 10:42 UTC, merged